[custom]

; ========== 规则集 ==========
ruleset=直连,[]GEOIP,private,no-resolve
ruleset=直连,[]GEOSITE,private
ruleset=直连,clash-classic:https://raw.githubusercontent.com/jhbook/meta-rules/refs/heads/main/direct.list
ruleset=🚀 默认代理,clash-classic:https://raw.githubusercontent.com/jhbook/meta-rules/refs/heads/main/proxy.list
ruleset=直连,[]GEOSITE,steam@cn
ruleset=🤖 ChatGPT,[]GEOSITE,category-ai-!cn
ruleset=👨🏻‍💻 GitHub,[]GEOSITE,github
ruleset=🐬 OneDrive,[]GEOSITE,onedrive
ruleset=直连,[]GEOSITE,microsoft
ruleset=直连,[]GEOSITE,apple
ruleset=📹 YouTube,[]GEOSITE,youtube
ruleset=直连,[]GEOSITE,ookla-speedtest
ruleset=🍀 Google,[]GEOSITE,google
ruleset=🎥 NETFLIX,[]GEOSITE,netflix
ruleset=🎵 TikTok,[]GEOSITE,tiktok
ruleset=💶 PayPal,[]GEOSITE,paypal
ruleset=📲 Telegram,[]GEOSITE,telegram
ruleset=直连,[]GEOSITE,cn
ruleset=直连,[]GEOIP,cn,no-resolve
ruleset=🚀 默认代理,[]GEOSITE,geolocation-!cn
ruleset=🐟 漏网之鱼,[]FINAL

; ========== 策略组 ==========
custom_proxy_group=🚀 默认代理`select`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

custom_proxy_group=📹 YouTube`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

custom_proxy_group=🍀 Google`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

custom_proxy_group=🤖 ChatGPT`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

custom_proxy_group=👨🏻‍💻 GitHub`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

custom_proxy_group=🐬 OneDrive`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

custom_proxy_group=🎵 TikTok`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

custom_proxy_group=📲 Telegram`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

custom_proxy_group=🎥 NETFLIX`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 狮城故转`[]🔯 香港故转`[]🔯 日本故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

custom_proxy_group=💶 PayPal`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 日本故转`[]🔯 香港故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

custom_proxy_group=🐟 漏网之鱼`select`[]🚀 默认代理`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]直连

; 地区手动选择
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|(?i)Hong)^((?!(台|日|韩|新|深|美)).)*$
custom_proxy_group=🇯🇵 日本节点`select`(日|JP|(?i)Japan)^((?!(港|台|韩|新|美)).)*$
custom_proxy_group=🇸🇬 狮城节点`select`(新加坡|坡|狮城|SG|Singapore)^((?!(台|日|韩|深|美)).)*$

; 故障转移
custom_proxy_group=🔯 香港故转`fallback`(港|HK|(?i)Hong)^((?!(台|日|韩|新|深|美)).)*$`https://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 日本故转`fallback`(日|JP|(?i)Japan)^((?!(港|台|韩|新|美)).)*$`https://www.gstatic.com/generate_204`180
custom_proxy_group=🔯 狮城故转`fallback`(新加坡|坡|狮城|SG|Singapore)^((?!(台|日|韩|深|美)).)*$`https://www.gstatic.com/generate_204`180

; 自动测速（核心）
custom_proxy_group=♻️ 香港自动`url-test`(港|HK|(?i)Hong)^((?!(台|日|韩|新|深|美)).)*$`https://www.gstatic.com/generate_204`180,20
custom_proxy_group=♻️ 日本自动`url-test`(日|JP|(?i)Japan)^((?!(港|台|韩|新|美)).)*$`https://www.gstatic.com/generate_204`180,20
custom_proxy_group=♻️ 美国自动`url-test`(美|US|USA|(?i)United States|(?i)America)^((?!(港|台|韩|日|新)).)*$`https://www.gstatic.com/generate_204`180,20
custom_proxy_group=♻️ 台湾自动`url-test`(台|TW|(?i)Taiwan)^((?!(港|韩|日|新|美)).)*$`https://www.gstatic.com/generate_204`180,20
custom_proxy_group=♻️ 韩国自动`url-test`(韩|KR|(?i)Korea)^((?!(港|台|日|新|美)).)*$`https://www.gstatic.com/generate_204`180,20
custom_proxy_group=♻️ 新加坡自动`url-test`(新加坡|坡|狮城|SG|Singapore)^((?!(港|台|韩|日|美)).)*$`https://www.gstatic.com/generate_204`180,20
custom_proxy_group=♻️ 自动选择`url-test`^((?!(直连)).)*$`https://www.gstatic.com/generate_204`180,20

; 手动节点 + 直连
custom_proxy_group=🌐 手动节点`select`.*
custom_proxy_group=直连`select`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true
