[custom]

; =========================================================
; 节点策略组
; =========================================================

custom_proxy_group=🚀 默认代理`select`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT

custom_proxy_group=📹 YouTube`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT

custom_proxy_group=🍀 Google`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT

custom_proxy_group=🤖 ChatGPT`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT

custom_proxy_group=👨🏿‍💻 GitHub`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT

custom_proxy_group=🐬 OneDrive`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT

custom_proxy_group=🎵 TikTok`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT

custom_proxy_group=📲 Telegram`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT

custom_proxy_group=🎥 NETFLIX`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 狮城故转`[]🔯 香港故转`[]🔯 日本故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT

custom_proxy_group=💶 PayPal`select`[]🚀 默认代理`[]♻️ 自动选择`[]🔯 日本故转`[]🔯 香港故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT

custom_proxy_group=🐟 漏网之鱼`select`[]🚀 默认代理`[]🔯 香港故转`[]🔯 日本故转`[]🔯 狮城故转`[]♻️ 美国自动`[]♻️ 台湾自动`[]♻️ 韩国自动`[]♻️ 香港自动`[]♻️ 日本自动`[]♻️ 新加坡自动`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🌐 手动节点`[]DIRECT


; =========================================================
; 地区节点
; =========================================================

custom_proxy_group=🇭🇰 香港节点`select`(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$

custom_proxy_group=🇯🇵 日本节点`select`(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$

custom_proxy_group=🇸🇬 狮城节点`select`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(台|日|韩|深|美)).)*$


; =========================================================
; 故障转移
; =========================================================

custom_proxy_group=🔯 香港故转`fallback`(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$`http://www.gstatic.com/generate_204`180

custom_proxy_group=🔯 日本故转`fallback`(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$`http://www.gstatic.com/generate_204`180

custom_proxy_group=🔯 狮城故转`fallback`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(台|日|韩|深|美)).)*$`http://www.gstatic.com/generate_204`180


; =========================================================
; 自动选择
; =========================================================

custom_proxy_group=♻️ 香港自动`url-test`(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$`http://www.gstatic.com/generate_204`180,,20

custom_proxy_group=♻️ 日本自动`url-test`(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$`http://www.gstatic.com/generate_204`180,,20

custom_proxy_group=♻️ 美国自动`url-test`(?=.*(美|US|USA|(?i)United States|(?i)America))^((?!(港|台|韩|日|新)).)*$`http://www.gstatic.com/generate_204`180,,20

custom_proxy_group=♻️ 台湾自动`url-test`(?=.*(台|TW|(?i)Taiwan))^((?!(港|韩|日|新|美)).)*$`http://www.gstatic.com/generate_204`180,,20

custom_proxy_group=♻️ 韩国自动`url-test`(?=.*(韩|KR|(?i)Korea))^((?!(港|台|日|新|美)).)*$`http://www.gstatic.com/generate_204`180,,20

custom_proxy_group=♻️ 新加坡自动`url-test`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(台|日|韩|美)).)*$`http://www.gstatic.com/generate_204`180,,20

custom_proxy_group=♻️ 自动选择`url-test`^((?!(DIRECT)).)*$`http://www.gstatic.com/generate_204`180,,20

custom_proxy_group=🌐 手动节点`select`.*


; =========================================================
; 规则集
; =========================================================

ruleset=DIRECT,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
ruleset=DIRECT,https://raw.githubusercontent.com/jhbook/meta-rules/refs/heads/main/direct.list
ruleset=🚀 默认代理,https://raw.githubusercontent.com/jhbook/meta-rules/refs/heads/main/proxy.list
ruleset=DIRECT,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs
ruleset=🤖 ChatGPT,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs
ruleset=🐬 OneDrive,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs
ruleset=DIRECT,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs
ruleset=DIRECT,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs
ruleset=📹 YouTube,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs
ruleset=DIRECT,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs
ruleset=🍀 Google,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs
ruleset=🎥 NETFLIX,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs
ruleset=🎵 TikTok,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs
ruleset=💶 PayPal,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs
ruleset=📲 Telegram,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs
ruleset=DIRECT,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs
ruleset=DIRECT,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs

; 国外域名
ruleset=🚀 默认代理,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs

; 最终规则
ruleset=🐟 漏网之鱼,[]FINAL

enable_rule_generator=true
overwrite_original_rules=true
